// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"net/http"

	"github.com/go-openapi/runtime/middleware"
)

// GetCheckpointsHandlerFunc turns a function with the right signature into a get checkpoints handler
type GetCheckpointsHandlerFunc func(GetCheckpointsParams) middleware.Responder

// Handle executing the request and returning a response
func (fn GetCheckpointsHandlerFunc) Handle(params GetCheckpointsParams) middleware.Responder {
	return fn(params)
}

// GetCheckpointsHandler interface for that can handle valid get checkpoints params
type GetCheckpointsHandler interface {
	Handle(GetCheckpointsParams) middleware.Responder
}

// NewGetCheckpoints creates a new http.Handler for the get checkpoints operation
func NewGetCheckpoints(ctx *middleware.Context, handler GetCheckpointsHandler) *GetCheckpoints {
	return &GetCheckpoints{Context: ctx, Handler: handler}
}

/*
	GetCheckpoints swagger:route GET /checkpoints getCheckpoints

Get a list of checkpoints.
*/
type GetCheckpoints struct {
	Context *middleware.Context
	Handler GetCheckpointsHandler
}

func (o *GetCheckpoints) ServeHTTP(rw http.ResponseWriter, r *http.Request) {
	route, rCtx, _ := o.Context.RouteInfo(r)
	if rCtx != nil {
		*r = *rCtx
	}
	var Params = NewGetCheckpointsParams()
	if err := o.Context.BindValidRequest(r, route, &Params); err != nil { // bind params
		o.Context.Respond(rw, r, route.Produces, route, err)
		return
	}

	res := o.Handler.Handle(Params) // actually handle the request
	o.Context.Respond(rw, r, route.Produces, route, res)

}
