// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the generate command

import (
	"errors"
	"net/url"
	golangswaggerpaths "path"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// GetImagesURL generates an URL for the get images operation
type GetImagesURL struct {
	After      *strfmt.DateTime
	Before     *strfmt.DateTime
	Checkpoint *string
	Limit      *int64
	Order      *string
	Page       *int64
	Query      *string
	Size       *string

	_basePath string
	// avoid unkeyed usage
	_ struct{}
}

// WithBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetImagesURL) WithBasePath(bp string) *GetImagesURL {
	o.SetBasePath(bp)
	return o
}

// SetBasePath sets the base path for this url builder, only required when it's different from the
// base path specified in the swagger spec.
// When the value of the base path is an empty string
func (o *GetImagesURL) SetBasePath(bp string) {
	o._basePath = bp
}

// Build a url path and query string
func (o *GetImagesURL) Build() (*url.URL, error) {
	var _result url.URL

	var _path = "/images"

	_basePath := o._basePath
	if _basePath == "" {
		_basePath = "/api/v1"
	}
	_result.Path = golangswaggerpaths.Join(_basePath, _path)

	qs := make(url.Values)

	var afterQ string
	if o.After != nil {
		afterQ = o.After.String()
	}
	if afterQ != "" {
		qs.Set("after", afterQ)
	}

	var beforeQ string
	if o.Before != nil {
		beforeQ = o.Before.String()
	}
	if beforeQ != "" {
		qs.Set("before", beforeQ)
	}

	var checkpointQ string
	if o.Checkpoint != nil {
		checkpointQ = *o.Checkpoint
	}
	if checkpointQ != "" {
		qs.Set("checkpoint", checkpointQ)
	}

	var limitQ string
	if o.Limit != nil {
		limitQ = swag.FormatInt64(*o.Limit)
	}
	if limitQ != "" {
		qs.Set("limit", limitQ)
	}

	var orderQ string
	if o.Order != nil {
		orderQ = *o.Order
	}
	if orderQ != "" {
		qs.Set("order", orderQ)
	}

	var pageQ string
	if o.Page != nil {
		pageQ = swag.FormatInt64(*o.Page)
	}
	if pageQ != "" {
		qs.Set("page", pageQ)
	}

	var queryQ string
	if o.Query != nil {
		queryQ = *o.Query
	}
	if queryQ != "" {
		qs.Set("query", queryQ)
	}

	var sizeQ string
	if o.Size != nil {
		sizeQ = *o.Size
	}
	if sizeQ != "" {
		qs.Set("size", sizeQ)
	}

	_result.RawQuery = qs.Encode()

	return &_result, nil
}

// Must is a helper function to panic when the url builder returns an error
func (o *GetImagesURL) Must(u *url.URL, err error) *url.URL {
	if err != nil {
		panic(err)
	}
	if u == nil {
		panic("url can't be nil")
	}
	return u
}

// String returns the string representation of the path with query string
func (o *GetImagesURL) String() string {
	return o.Must(o.Build()).String()
}

// BuildFull builds a full url with scheme, host, path and query string
func (o *GetImagesURL) BuildFull(scheme, host string) (*url.URL, error) {
	if scheme == "" {
		return nil, errors.New("scheme is required for a full url on GetImagesURL")
	}
	if host == "" {
		return nil, errors.New("host is required for a full url on GetImagesURL")
	}

	base, err := o.Build()
	if err != nil {
		return nil, err
	}

	base.Scheme = scheme
	base.Host = host
	return base, nil
}

// StringFull returns the string representation of a complete url
func (o *GetImagesURL) StringFull(scheme, host string) string {
	return o.Must(o.BuildFull(scheme, host)).String()
}
