// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"

	"github.com/go-openapi/runtime"

	"github.com/jkawamoto/sd-image-viewer/server/models"
)

// GetImagesOKCode is the HTTP code returned for type GetImagesOK
const GetImagesOKCode int = 200

/*
GetImagesOK A list of images.

swagger:response getImagesOK
*/
type GetImagesOK struct {

	/*
	  In: Body
	*/
	Payload *models.ImageList `json:"body,omitempty"`
}

// NewGetImagesOK creates GetImagesOK with default headers values
func NewGetImagesOK() *GetImagesOK {

	return &GetImagesOK{}
}

// WithPayload adds the payload to the get images o k response
func (o *GetImagesOK) WithPayload(payload *models.ImageList) *GetImagesOK {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get images o k response
func (o *GetImagesOK) SetPayload(payload *models.ImageList) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImagesOK) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(200)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}

/*
GetImagesDefault Error Response

swagger:response getImagesDefault
*/
type GetImagesDefault struct {
	_statusCode int

	/*
	  In: Body
	*/
	Payload *models.StandardError `json:"body,omitempty"`
}

// NewGetImagesDefault creates GetImagesDefault with default headers values
func NewGetImagesDefault(code int) *GetImagesDefault {
	if code <= 0 {
		code = 500
	}

	return &GetImagesDefault{
		_statusCode: code,
	}
}

// WithStatusCode adds the status to the get images default response
func (o *GetImagesDefault) WithStatusCode(code int) *GetImagesDefault {
	o._statusCode = code
	return o
}

// SetStatusCode sets the status to the get images default response
func (o *GetImagesDefault) SetStatusCode(code int) {
	o._statusCode = code
}

// WithPayload adds the payload to the get images default response
func (o *GetImagesDefault) WithPayload(payload *models.StandardError) *GetImagesDefault {
	o.Payload = payload
	return o
}

// SetPayload sets the payload to the get images default response
func (o *GetImagesDefault) SetPayload(payload *models.StandardError) {
	o.Payload = payload
}

// WriteResponse to the client
func (o *GetImagesDefault) WriteResponse(rw http.ResponseWriter, producer runtime.Producer) {

	rw.WriteHeader(o._statusCode)
	if o.Payload != nil {
		payload := o.Payload
		if err := producer.Produce(rw, payload); err != nil {
			panic(err) // let the recovery middleware deal with this
		}
	}
}
