// Code generated by go-swagger; DO NOT EDIT.

// Package restapi SD Image Viewer API
//
//	Schemes:
//	  http
//	Host: localhost:8080
//	BasePath: /api/v1
//	Version: 2023-04-23
//
//	Consumes:
//	  - application/json
//
//	Produces:
//	  - image/png
//	  - application/json
//
// swagger:meta
package restapi
