name: Go application

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
        with:
          go-version: ">=1.20"
      - name: Run tests
        run: go test --tags mock -race -v ./...
      - uses: actions/setup-node@v3
        with:
          node-version: ">=19.9.0"
          cache: yarn
          cache-dependency-path: frontend/yarn.lock
      - name: Install frontend dependencies
        run: yarn --cwd ./frontend
      - name: Run pre-commit hook
        uses: pre-commit/action@v3.0.0
      - name: Build
        uses: goreleaser/goreleaser-action@v4
        with:
          version: latest
          args: build --snapshot
